---
title: "Project 2"
author: "Author 1, Author 2, Author 3"
output: 
  pdf_document: 
    toc: yes
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE, tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

\newpage

# Problem 1

## a)

## b)

```{r}
set.seed(97)
lam = 5
mu = 6

# Initial conditions
x = c(0)
s = c(0)

# Simulate forward in time
B = 11908
for(i in 1:B){
   cState = x[i]
   if(cState == 0){
      s = c(s, tail(s,1)+rexp(n = 1, rate = lam))
      x = c(x, 1)
   } else{
      s = c(s, tail(s,1) + rexp(n = 1, rate = lam+mu))
      if(runif(1) < lam/(lam+mu)){
         x = c(x, cState+1)
      } else{
         x = c(x, cState-1)
      }
   }
}
```

```{r eval=FALSE, include=FALSE}
# # 24 hours
# plot(NULL, NULL, xlim = c(0, 24), ylim = c(0, 30), xlab = "Time (h)", ylab = "Number of customers in system", cex.axis = 1.5, cex.lab = 1.5)
# for(i in 1:200){
#    lines(s[i:(i+1)], rep(x[i],2), lwd = 2)
# }
# 
# # 1 day
# plot(NULL, NULL, xlim = c(0, 1), ylim = c(0, 30), xlab = "Time (day)", ylab = "Number of customers in system", cex.axis = 1.5, cex.lab = 1.5)
# for (i in 1:200) {
#    lines(s[i:(i+1)]/24, rep(x[i],2), lwd = 2)
# }

# 50 days
plot(NULL, NULL, xlim = c(0, 50), ylim = c(0, 45), xlab = "Time (day)", ylab = "Number of customers in system", cex.axis = 1.5, cex.lab = 1.5)
for (i in 1:1e5) {
   lines(s[i:(i+1)]/24, rep(x[i],2), lwd = 2)
}
```

```{r}
table(x)
```

```{r}
numT = rep(0, 50)
hmm = 0
for(i in 1:(length(x)-1)){
   numT[x[i]+1] = numT[x[i]+1] + s[i+1] - s[i]
   hmm = hmm + s[i+1] - s[i]
}
barplot(numT/s[length(x)], names.arg = 0:(length(numT)-1), xlab = "Number of customers in system", ylab = "Mean fraction of time", cex.axis = 1.5, cex.lab = 1.5, cex = 1.5)

# Expected number of requests in the system
print("Average number of requests in the system:")
pi = numT/s[length(x)-1]
L = sum((0:49)*pi)
print(L)

# Expected waiting time
cat("Exptected time spent in system:", L / lam, "hour(s)")
```

```{r}
# 12 hours
plot(NULL, NULL, xlim = c(0, 12), ylim = c(0, 30), xlab = "Time (h)", ylab = "Number of customers in system", cex.axis = 1.5, cex.lab = 1.5)
for (i in 1:119) {
   lines(s[i:(i+1)], rep(x[i],2), lwd = 2)
}
```

## c)

## d)

## e)

## f)

## g)

\newpage

# Problem 2

## a)

```{r}
set.seed(98)
xx <- seq(0.25, 0.50, 0.005)

mu = rep(0.5, length(xx))
Sig = matrix(0, nrow = length(xx), ncol = length(xx))
for(i in 1:length(xx)){
   for (j in 1:length(xx)) {
      Sig[i,j] = 0.5^2 * (1 - 15 * abs(xx[i]-xx[j])) * exp(-15 * abs(xx[i]-xx[j]))
   }
}

SigC = Sig - Sig[,c(11, 21, 29, 33, 41), drop = FALSE]%*%solve(Sig[c(11, 21, 29, 33, 41), c(11, 21, 29, 33, 41), drop = FALSE], Sig[c(11, 21, 29, 33, 41),, drop = FALSE])

muC = mu + Sig[,c(11, 21, 29, 33, 41),drop = FALSE]%*%solve(Sig[c(11, 21, 29, 33, 41),c(11, 21, 29, 33, 41),drop = FALSE], c(0.5, 0.32, 0.40, 0.35, 0.60) - mu[c(11, 21, 29, 33, 41)])

nR = 100
yMat = matrix(0, nrow = nR, ncol = length(xx))
Lt = t(chol(SigC+diag(length(xx))*1e-8))
for (i in 1:nR) {
   yMat[i,] = Lt%*%rnorm(length(xx))+muC
}

# Plot
plot(NULL, NULL, xlim = c(xx[1], tail(xx,1)), ylim = c(-1, 2), xlab = "Theta", ylab = "y(theta)", cex.axis = 1.5, cex.lab = 1.5, lwd = 1.5)
# for (i in 1:100) {
#    lines(xx, yMat[i,], col = 1, lwd = 1.5)
# }

lines(xx, muC, col = "red", lwd = 2)
lines(xx, muC + 1.64*sqrt(diag(SigC)), col = "green", lwd = 2)
lines(xx, muC - 1.64*sqrt(diag(SigC)), col = "green", lwd = 2)

lines(c(0.25, 0.50), c(0.30, 0.30), col = "blue", lwd = 1.5, lty = 4)

legend(x= "topright", y=0.80, legend=c("Mean", "C.I.", "y(theta) = 0.30"), col=c("red", "green", "blue"), lty= 1:2, cex=0.8)
```

## b)

```{r}
z0 <- rep(0, length(muC))
for (i in 1:length(muC)) {
   z0[i] <- (0.30 - muC[i])/(sqrt(diag(SigC))[i])
}

plot(NULL, NULL, xlim = c(xx[1], tail(xx,1)), ylim = c(0, 1), xlab = "theta", ylab = "P(Y(theta) < 0.30)", cex.axis = 1.5, cex.lab = 1.5, lwd = 1.5)
for (i in 1:length(z0)) {
   points(xx[i], pnorm(z0[i]), col = 1, lwd = 1.5)
}
```

## c)

```{r}
set.seed(98)
xx <- seq(0.25, 0.50, 0.005)

mu = rep(0.5, length(xx))
Sig = matrix(0, nrow = length(xx), ncol = length(xx))
for(i in 1:length(xx)){
   for (j in 1:length(xx)) {
      Sig[i,j] = 0.5^2 * (1 - 15 * abs(xx[i]-xx[j])) * exp(-15 * abs(xx[i]-xx[j]))
   }
}

SigC = Sig - Sig[,c(11, 17, 21, 29, 33, 41), drop = FALSE]%*%solve(Sig[c(11, 17, 21, 29, 33, 41), c(11, 17, 21, 29, 33, 41), drop = FALSE], Sig[c(11, 17, 21, 29, 33, 41),, drop = FALSE])

muC = mu + Sig[,c(11, 17, 21, 29, 33, 41),drop = FALSE]%*%solve(Sig[c(11, 17, 21, 29, 33, 41),c(11, 17, 21, 29, 33, 41),drop = FALSE], c(0.5, 0.40, 0.32, 0.40, 0.35, 0.60) - mu[c(11, 17, 21, 29, 33, 41)])

nR = 100
yMat = matrix(0, nrow = nR, ncol = length(xx))
Lt = t(chol(SigC+diag(length(xx))*1e-8))
for (i in 1:nR) {
   yMat[i,] = Lt%*%rnorm(length(xx))+muC
}

# Plot
plot(NULL, NULL, xlim = c(xx[1], tail(xx,1)), ylim = c(-1, 2), xlab = "Theta", ylab = "y(theta)", cex.axis = 1.5, cex.lab = 1.5, lwd = 1.5)
# for (i in 1:100) {
#    lines(xx, yMat[i,], col = 1, lwd = 1.5)
# }

lines(xx, muC, col = "red", lwd = 2)
lines(xx, muC + 1.64*sqrt(diag(SigC)), col = "green", lwd = 2)
lines(xx, muC - 1.64*sqrt(diag(SigC)), col = "green", lwd = 2)

lines(c(0.25, 0.50), c(0.30, 0.30), col = "blue", lwd = 1.5, lty = 4)

legend(x= "topright", y=0.92, legend=c("Mean", "C.I.", "y(theta) = 0.30"), col=c("red", "green", "blue"), lty= 1:2, cex=0.8)
```

```{r}
z0 <- rep(0, length(muC))
for (i in 1:length(muC)) {
   z0[i] <- (0.30 - muC[i])/(sqrt(diag(SigC))[i])
}

plot(NULL, NULL, xlim = c(xx[1], tail(xx,1)), ylim = c(0, 1), xlab = "theta", ylab = "P(Y(theta) < 0.30)", cex.axis = 1.5, cex.lab = 1.5, lwd = 1.5)

pnormc <- rep(0, length(z0))

for (i in 1:length(z0)) {
   pnormc[i] <- pnorm(z0[i])
   points(xx[i], pnorm(z0[i]), col = 1, lwd = 1.5)
}

abline(v = xx[which.max(pnormc)], col="red")

cat("Largest prob. is", max(pnormc), "and this is given when theta =", xx[which.max(pnormc)])
```

For the biggest probability of getting $y(\theta) < 0.30$, they should use $\theta = 0.355$. This gives the larges probability.
