---
title: "TMA4265 Stochastic Modelling: Solution Exercise 8"
author: "Week 43"
output: pdf_document
header-includes:
  - \geometry{top=1in}
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\Huge\bfseries}
  - \posttitle{\end{flushleft}}  
  - \preauthor{\begin{flushleft}\Large}
  - \postauthor{\end{flushleft}}  
  - \predate{\begin{flushleft}\large}
  - \postdate{\end{flushleft}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

SINTEF researchers are considering five sites near Stavanger 
for a possible CO$_{2}$ injection and storage project. 
Assume the CO$_{2}$ saturations 
in these locations can be modelled as a multivariate Gaussian:
$\boldsymbol{x}=(x_{1},x_{2},x_{3},x_{4},x_{5})\sim\mathcal{N}_5(\boldsymbol{\mu}, \Sigma)$, with
$\boldsymbol{\mu}=(1.6,1.5,1.2,1.0,1.1)$ and
$\Sigma=\mathbf{I}_{5}$.


1. Calculate the probability that the saturation values in the locations simultaneously exceed 1. 

2. After careful investigations, the researchers have found that a more accurate model is an exchangeable model, where $\text{Var}[x_i] = 1.5$ for $i = 1, 2, \ldots, 5$ and $\text{Corr}[x_i, x_j] = 0.25$ for $i\neq j$. Calculate the resulting covariance matrix $\Sigma_\mathrm{E}$ in this case.

3. The researchers have discovered that only sites 2 and 5 are of interest, i.e., $x_{2}$ and $x_{5}$. What is the joint distribution of $(x_{2},x_{5})$ if the joint distribution of $\boldsymbol{x}\sim\mathcal{N}_5(\boldsymbol{\mu}, \Sigma_\mathrm{E})$?

# Problem 2

Consider the stock price of Telenor tomorrow. Let $x_1$ be the value at 10:00 and $x_2$ be the value at 11:00. Assume that a reasonable model for the stock prices is $(x_1,x_2)\sim\mathcal{N}_2(\boldsymbol{\mu}, \Sigma)$, where
$$
\boldsymbol{\mu}=(180, 180) \,\,\,\,\text{and}\,\,\,\, \boldsymbol{\Sigma}= \left[\begin{array}{cc}
16 & 15\\
15 & 25
\end{array}\right]
$$

We observe that the stock price at 10:00 is 175 kr.


1. Find the conditional mean and  variance of the  stock price at 11:00, $x_2\vert x_1 = 175$.

2. Calculate the conditional probability that the stock price at 11:00 is less than 170.

# Problem 3

Exercise D from the GP note.


