---
title: "TMA4265 Stochastic Modelling: Exercise 5"
author: "Week 38"
output: pdf_document
header-includes:
  - \geometry{top=1in}
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\Huge\bfseries}
  - \posttitle{\end{flushleft}}  
  - \preauthor{\begin{flushleft}\Large}
  - \postauthor{\end{flushleft}}  
  - \predate{\begin{flushleft}\large}
  - \postdate{\end{flushleft}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

Exercises from the book

**a)** 5.1.1) Defects occur along the length of a filament (according to a Poisson process) at a rate $\lambda=2$ per foot.

   (i) Calculate the probability that there are no defects in the first foot of the filament.
  (ii) Calculate the conditional probability that there are no defects in the second foot of the filament, given that the first foot contained a single defect.
	
**b)** (5.1.2) Let $p_k=\text{Pr}\{x=k\}$ be the probability mass function corresponding to a Poisson distribution with parameter $\lambda$. Verify that $p_0 = \exp\{- \lambda \}$, and that $p_k$ may be computed recursively by $p_k=(\lambda/k)p_{k-1}$.

**c)** (5.1.3) Let \textit{X} and \textit{Y} be independent Poisson distributed random variables with parameters $\alpha$ and $\beta$, respectively. Determine the conditional distribution of \textit{X}, given that \textit{N=X+Y=n}.

**d)** (5.3.1) A radioactive source emits particles according to a Poisson process of rate $\lambda=2$ particles per minute. What is the probability that the first particle appears after 3 min?

**e)** (5.3.2) A radioactive source emits particles according to a Poisson process of rate $\lambda=2$ particles per minute. 
  
  (i) What is the probability that the first particle appears some time after 3 min but before 5 min? 
  (ii) What is the probability that exactly one particle is emitted in the interval from 3 to 5 min?
	
**f)** (5.3.3) Customers enter a store according to a Poisson process of rate $\lambda=6$ per hour. Suppose it is known that only a single customer entered during the first hour. What is the conditional probability that this person entered during the first 15 min?

**g)** (5.4.1) Let $\{X(t): t \geq 0\}$ be a Poisson process of rate $\lambda$. Suppose it known that $X(1) = n$. For $n = 1, 2, \ldots$, determine the mean of the first arrival time $W_1$.

# Problem 2: Football

The number of goals scored by V책lerenga IF during a football match is Poisson distributed with an average of $\lambda_v=1.2$ goals per match while the number of goals scored by Rosenborg BK is Poisson distributed with an average of $\lambda_r=2$ goals per match. The number of goals scored by V책lerenga is independent of the number of goals scored by Rosenborg. Assume that a football match lasts for exactly 90 minutes ($2 \times 45$ minutes) and that V책lerenga plays a match against Rosenborg:

**a)** What is the distribution for the total number of goals scored in this match?

**b)** What is the probability that there are no goals during the first half of the match?

**c)**  What is the probability that the final result is 2--2?

**d)**  What is the expected time until the first goal in this match?

**e)** Assume that no goals are scored the first 15 minutes of the match. What is the probability that V책lerenga score at least one goal before the break at 45 minutes?

**f)** Verify your theoretical answers by simulations in R. Some useful functions are \texttt{rpois()} and \texttt{rexp()}.





