---
title: "TMA4265 Stochastic Modelling: Exercise 6"
author: "Week 41"
output: pdf_document
header-includes:
  - \geometry{top=1in}
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\Huge\bfseries}
  - \posttitle{\end{flushleft}}  
  - \preauthor{\begin{flushleft}\Large}
  - \postauthor{\end{flushleft}}  
  - \predate{\begin{flushleft}\large}
  - \postdate{\end{flushleft}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1 -- Exercises 6.1.1 and 6.1.2 in the book
A pure birth process starting from $X(0) = 0$ has birth parameters
$\lambda_0 = 1$, $\lambda_1 = 3$, $\lambda_2 = 2$ and $\lambda_3 = 5$. Let
$W_1$, $W_2$ and $W_3$ be the stochastic times it takes the process to
reach states 1, 2 and 3, respectively.

**a)** Determine the transition probability functions $P_n(t) = \text{Pr}\{X(t) = n|X(0) = 0\}$ for $n = 0, 1, 2, 3$. \emph{Hint: Read Section 6.1.2 in the book, and remember what we did in the lectures.}

**b)** Write $W_3$ as a sum of sojourn times and thereby deduce that the mean time is
	$\mathrm{E}[W_3] = \frac{11}{6}$.
	
**c)** Determine the mean of $W_1 + W_2 + W_3$.

**d)** Determine the variance of $W_3$.


# Problem 2: Parking garage

A parking garage opens at 08:00 and closes at 16:00. 
We model the arrival of cars to the parking garage during opening hours as a Poisson process with rate $\lambda = 0.5$ cars/min. In part \textbf{a)} and \textbf{b)}, we assume that the garage has room for infinitely many cars.

**a)**

- Calculate the probability that no car has arrived at 08:05.
- Compute the expected number of cars that will arrive during the first 15 minutes of opening hours.
- Given that two cars will arrive during the first 10 minutes, compute the probability that no cars arrive during the first 5 minutes.
	
**b)** Customers spend on average $100\,\mathrm{kr}$ for parking, independently of each other, with standard deviation of $10\, \mathrm{kr}$.

  - Calculate the expected value of the total income at the garage during one day.
  - Calculate the variance of the total income at the garage during one day.

\noindent
Assume additionally that cars, independently of each other and their arrival times, spend a stochastic time in the parking garage, which follows an exponential distribution with expectation $1/\mu = 30$ minutes. After the time has passed, the car immediately exists the parking garage. Further, the parking garage has a maximum capacity of $N_{\mathrm{max}} = 20$ cars, and cars that arrive when the garage is full will drive
past the garage without forming a queue. Under these assumptions, the number of cars $X(t)$ in the garage at time $t$ is a birth-and-death process.

**c)**

  - Determine the birth and death rates of the process.
  - Draw a transition diagram for the process.
  - Two cars are in the parking garage at 16:00, and no new cars may enter. The two cars will leave according to the rates described above. Let
  $T$ be the time until the parking garage is empty, and determine the probability density, $f_T(t)$.

**d)** Ignore the opening hours and assume that the parking garage is always open. There are currently 16 cars in the parking garage.
		
  - Determine the distribution of the time until the number of cars in the garage changes.
  - Calculate the probability that the next time the number of cars in the garage changes, it will be a car that leaves.


