---
title: "TMA4265 Stochastic Modelling: Exercise 7"
author: "Week 42"
output: pdf_document
header-includes:
  - \geometry{top=1in}
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\Huge\bfseries}
  - \posttitle{\end{flushleft}}  
  - \preauthor{\begin{flushleft}\Large}
  - \postauthor{\end{flushleft}}  
  - \predate{\begin{flushleft}\large}
  - \postdate{\end{flushleft}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1 -- A continuation of the parking garage (week 41)

Assume that a parking garage has a maximum capacity of 20 cars and is always open. The arrival
of cars is a Poisson process with rate $\lambda = 0.5$ cars/min, where cars will drive past the garage (and not form a queue) if the parking garage is full. The cars spend, independently of each other and their arrival times, a stochastic time in the parking garage. Each stochastic time follows an exponential distribution with expected value $1/\mu = 30$ minutes. After the time in the parking garage ends, the car immediately exists the parking garage. In the exercise sheet for week 41, you found the birth and death rates of the resulting birth-and-death process.

**a)** Determine the limiting probabilities $\pi_{i}$, $i = 0,1, \ldots, 20$, as functions of $\lambda$ and $\mu$, and then compute the numerical value of $\pi_{20}$.
				
**b)** Compute the numerical value of the long-run mean number of cars in the parking garage.

# Problem 2 -- General continuous-time Markov chains
	
A tourist guide can be hired to give sightseeing tours with his boat. If the guide is free, the time it takes an interested tourist to negotiate the price is exponentially distributed with mean $1/\mu_{1}$. Assume that the probability that no agreement is reached and the tourist leaves is $0 < \alpha < 1$. If the tourist and the guide reach an agreement, they immediately start the tour. The duration of the tour is exponentially distributed with mean $1/\mu_{2}$. Assume that interested tourists arrive at the harbor according to a Poisson process with rate $\lambda$, but will not wait in line and leave immediately if the guide is not free. Assume further that the Poisson process, the negotiation time, the duration of the tour and whether the tourist and the guide achieve an agreement are independent.

**a)** Compute the long-run mean proportion of time that the guide is free.

**b)** You arrive at the harbor and see that the guide is currently negotating with a potential customer. Determine the expected time you would need to wait until the guide is free.

**c)** Determine the long-run proportion of the $\lambda$ tourists that arrive per time unit that will go on a sightseeing tour.

**d)** Assume that $\lambda = 10$ per hour, $1/\mu_1 = 5$ minutes, $1/\mu_2 = 30$ minutes, and $\alpha = 0.20$. Write computer code to verify the answers in a), b) and c) for the specified parameter values.

# Problem 3 -- Biathlon

 Biathlon commonly refers to the winter sport that combines cross-country skiing and rifle shooting. The inhabitants of Oslo want to improve their Biathlon skills, and go to a popular skiing area to train. There is a stadium with three public shooting stands available. Skiers arrive at the shooting stands according to a Poisson process with rate $5$ skiers per minute, i.e., $\lambda= 1/12$ skier per second.  If a shooting stand is free, an entering skier immediately starts to shoot and then immediately leaves the stadium when finished. If all stands are occupied, the skier waits in line and then goes to the first free shooting stand that becomes available. The time a skier spends at either of the shooting stands is independent of the other skiers and exponentially distributed with mean $30$ seconds, i.e., with rate $\mu= 1/30$ per second. 
Let $X(t)$ denote the number of skiers in the stadium at time $t$, i.e., skiers who are either shooting or waiting in line until a shooting stand becomes free. We assume that $X(0) = 0$.

**a)** Explain briefly why $\{X(t): t\geq 0\}$ is a birth-death process and give all birth and death rates.

**b)** If $X(t)=3$, what is the expected time until all the three skiers who are currently shooting have finished shooting.

**c)** Starting at time $0$, what is the expected time until $X(t)=3$ for the first time.


