---
title: "TMA4265 Stochastic Modelling: Exercise 3"
author: "Week 36"
output: pdf_document
header-includes:
  - \geometry{top=1in}
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\Huge\bfseries}
  - \posttitle{\end{flushleft}}  
  - \preauthor{\begin{flushleft}\Large}
  - \postauthor{\end{flushleft}}  
  - \predate{\begin{flushleft}\large}
  - \postdate{\end{flushleft}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

For each of the following transition probability matrices, determine if the corresponding Markov chain is regular.
$$
	\textbf{a)}\,\,
	\begin{bmatrix}
	0.9 & 0.1 \\
	1 & 0   \\
	\end{bmatrix},\,\,\,
	\textbf{b)}\,\,
	\begin{bmatrix}
	1 & 0 \\
	0 & 1   \\
	\end{bmatrix},\,\,\,
	\textbf{c)}
	\begin{bmatrix}
	0.9 & 0.1 \\
	0 & 1   \\
	\end{bmatrix},\,\,\,
	\textbf{d)}\,\,
	\begin{bmatrix}
	0.9 & 0.1 & 0 \\
	0   & 0   & 1   \\
	1   & 0   & 0 \\
	\end{bmatrix},\,\,\,
	\textbf{e)}\,\,
	\begin{bmatrix}
	0.9 & 0.1 & 0 \\
	0   & 0   & 1   \\
	0   & 1   & 0 \\
	\end{bmatrix}\,\,\,
$$


# Problem 2

Let $\{X_n: n = 0, 1, \ldots\}$, where $n$ denotes day, be a Markov chain with states "sun" (0), "light rain" (1), and "heavy rain" (2). The transition probability matrix is given by,
$$
\mathbf{P} = \begin{bmatrix} 0.40 & 0.45 & 0.15 \\
								 0.40 & 0.40 & 0.20 \\
								 0.20 & 0.40 & 0.40
				 \end{bmatrix}.
$$
Assume that John is a very hard-working individual who goes to work every single day of the week. 

**a)** Calculate the proportion of days with sun, the proportion of days with light rain, and the proportion of days with heavy rain.

**b)** If it is sunny, John will walk which costs 0 kr, but if it is light or heavy rain, he will take the bus which costs 80 kr for a day. In the long run, what is John's average daily cost for travelling to work?

**c)**  John is wondering if he is overpaying by buying single tickets each time, and decides to check prices for 30-day tickets. He discovers that 30-day tickets are cheaper than single tickets if he travels to work by bus more than 18 days per 30 day period. Should he continue to buy single tickets or
should he start buying 30-day tickets?

**d)** Assume that the first day ($n = 0$) is sunny and write code that simulates the weather 
for $N = 100000$ more days. Verify that you reached the correct conclusion in c).

# Problem 3

Consider the transition probability matrix

$$
 \mathbf{P} = \begin{bmatrix} p & q & 0 \\ 0 & p & q \\ q & 0 & p \end{bmatrix},
$$

where $p, q \geq 0$ and $p+q = 1$. Calculate the limiting probabilities $\pi_0$, $\pi_1$,
and $\pi_2$ as a function of $p$ and $q$.




