---
title: "TMA4265 Stochastic Modelling: Exercise 1"
author: "Week 34"
output: pdf_document
header-includes:
  - \geometry{top=1in}
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\Huge\bfseries}
  - \posttitle{\end{flushleft}}  
  - \preauthor{\begin{flushleft}\Large}
  - \postauthor{\end{flushleft}}  
  - \predate{\begin{flushleft}\large}
  - \postdate{\end{flushleft}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1: Coin toss

You have two coins in your pocket: a fair coin and a biased coin. The fair coin has two sides: "heads" and "tails". The biased coin has two sides: "heads" and "heads". A coin toss consists of three steps: select one coin completely at random from your pocket, flip it once, and note the result (`heads` or `tails`).

**a)** Compute the probability that the biased coin was selected given that the coin toss results in heads.

**b)** You decide to change the second step in the coin toss and flip twice instead of once. Assume that each flip is independent, and compute the probability that the biased coin was selected given that both flips result in heads.

**c)** The function \texttt{runif()} in \texttt{R} can be used to draw random numbers between 0 and 1 from a continuous uniform distribution. Explore how you can use one of the above functions to simulate the outcome of a coin toss. Next, write code that simulates that you pick one of the coins from your pocket and flip it once (as in 1a) or twice (as in 1b). Use your code to verify the analytic results in $\textbf{a)}$ and $\textbf{b)}$ numerically by simulating each situation $N$ times, where $N$ is a large number of your choice.

# Problem 2: Insurance claims

Let $N$ denote the number of claims (in hundreds) received by an insurance company during one specific year. Assume that the number of claims $N$ is Poisson distributed with expected value $\lambda=6$. Let the claim amounts be denoted by $C_1,\ldots,C_N$, and assume that each claim amount (in mill. kr.) has a log-Gaussian distribution with parameters $\mu=-2$ and $\sigma^2$=1, i.e., $C_i=\exp(Y_i)$ where $Y_i\sim \mathcal{N}(\mu,\sigma^2)$ for $i=1,...N$. The claim amounts are independent of each other and independent of the number of claims.

**a)** Show that for the log-Gaussian distribution $\text{E}[C_i]=\mu_c=\exp(\mu+\sigma^2/2)$ and $\text{Var}[C_i] =\sigma^2_c=\text{exp}(2\mu+ \sigma^2)(\text{exp}(\sigma^2)-1)$.

\textit{Hint: Consider the moment generating function of the normal distribution for $t = 1$ and $t = 2$.}

**b)** Use the law of iterated expectation and the law of total variance to compute the expected value of the total claim amount and the variance of the total claim amount, respectively. I.e., find $\text{E}[\sum_{i=1}^N C_i]$ and $\text{Var}[\sum_{i=1}^N C_i]$.

**c)** Write code in \texttt{R} that simulates the situation described in this problem. Use the code to verify the analytic answers in $\textbf{a)}$ and $\textbf{b)}$ numerically by simulating $B$ years of insurance claims where $B$ is a large number of your choice.

\emph{Hint: In \emph{\texttt{R}} you can use the functions \emph{\texttt{rpois()}} and \emph{\texttt{rlnorm()}}} to generate random values from the Poisson distribution and the log-Gaussian distribution respectively.
