---
title: "TMA4265 Stochastic Modelling: Exercise 4"
author: "Week 37"
output: pdf_document
header-includes:
  - \geometry{top=1in}
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\Huge\bfseries}
  - \posttitle{\end{flushleft}}  
  - \preauthor{\begin{flushleft}\Large}
  - \postauthor{\end{flushleft}}  
  - \predate{\begin{flushleft}\large}
  - \postdate{\end{flushleft}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

Consider the Markov chain $\{X_n: n = 0, 1, \ldots\}$ with transition probability matrix
$$
	\mathbf{P} = \begin{bmatrix} 0.50 & 0.50 & 0 & 0 & 0 & 0 \\
								 0.25 & 0.75 & 0 & 0 & 0 & 0 \\
								 0.25 & 0.25 & 0.25 & 0.25 & 0 & 0 \\
								 0.25 & 0    & 0.25 & 0.25 & 0 & 0.25 \\
								 0 & 0 & 0 & 0 & 0.50 & 0.50 \\
								 0 & 0 & 0 & 0 & 0.50 & 0.50 
				 \end{bmatrix}.
$$



**a)** Is the Markov chain reducible or irreducible? If it is reducible, specify
its equivalence classes.

**b)** Calculate the period of each state.

**c)** Which states are transient and which states are recurrent? Are there any absorbing states?

# Problem 2

Let $\{X_n: n = 0,1, \ldots\}$ be a Markov chain with finite state space $\{0, 1, \ldots, N\}$. Show that if the Markov chain is aperiodic and irreducible, then it is regular and recurrent.

# Problem 3

Consider the discrete-time Markov chain with transition probability matrix
$$
	\mathbf{P} = \begin{bmatrix} 0.9 & 0.1 & 0 \\
								 0.05 & 0.8 & 0.15 \\
								 0 & 0.1 & 0.9 
				 \end{bmatrix}.
$$


**a)** Is the Markov chain reducible or irreducible?


**b)** Calculate the limiting probability of each state.


**c)** Write code to simulate the Markov chain, and verify the answer in b) numerically.

# Problem 4

We throw a fair coin repeatedly, and denote each outcome by H (heads) or T (tails). Let $n$ denote the $n$-th throw in 
a sequence, and define a stochastic process $\{X_n: n = 0, 1, \ldots\}$ by
$$
	X_n = \text{"The number of consecutive throws of H, including throw }n", \quad n = 0, 1, \ldots.
$$


**a)** Explain why this is a Markov process. Specify the state space, and find the transition probabilities.

**b)** Is this Markov chain irreducible?

**c)** For each state, calculate its period.

**d)** Show that the states are recurrent.

**e)** Calculate the long run proportion of time that the sequence of throws ends in three or more heads.




